{
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "buildbot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384488",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371686"
    ],
    "summaries": [
      "buildbot: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: buildbot-master, buildbot-master-container, buildbot-master-ec2, buildbot-master-libvirt, buildbot-master-openstack, buildbot-worker, buildbot-www"
    ]
  },
  "cfn-lint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384496",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371692"
    ],
    "summaries": [
      "cfn-lint: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: cfn-lint+full, cfn-lint+graph, cfn-lint+junit, cfn-lint+sarif, cfn-lint"
    ]
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "copr-backend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351386"
    ],
    "summaries": [
      "copr-backend fails to build with Python 3.14: TestActionWorkerManager.test_add_task_for_running_worker: TypeError: cannot pickle 'itertools.count' object"
    ]
  },
  "dolfin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384554",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371707"
    ],
    "summaries": [
      "dolfin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-dolfin"
    ]
  },
  "libpeas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385122",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366247"
    ],
    "summaries": [
      "libpeas: FTBFS in Fedora rawhide/f43",
      "libpeas fails to build with Python 3.14: test-extension-py  TIMEOUT"
    ]
  },
  "mailman3-fedmsg-plugin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385168",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2304216"
    ],
    "summaries": [
      "mailman3-fedmsg-plugin: FTBFS in Fedora rawhide/f43",
      "F41FailsToInstall: python3-mailman3-fedmsg-plugin"
    ]
  },
  "matrix-synapse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385171",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371743"
    ],
    "summaries": [
      "matrix-synapse: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: Multiple packages built from matrix-synapse"
    ]
  },
  "mirrormanager2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385192",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2347031"
    ],
    "summaries": [
      "mirrormanager2: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: mirrormanager2"
    ]
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "paraview": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385379"
    ],
    "summaries": [
      "paraview: FTBFS in Fedora rawhide/f43"
    ]
  },
  "patool": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366470"
    ],
    "summaries": [
      "patool fails to build with Python 3.14: Codec Load Error: /usr/bin/7z.so : errno=25 : Inappropriate ioctl for device"
    ]
  },
  "psi4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385428",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371776"
    ],
    "summaries": [
      "psi4: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: psi4"
    ]
  },
  "pylint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368703"
    ],
    "summaries": [
      "pylint fails to build with Python 3.14: AssertionError tests/test_functional.py::test_functional"
    ]
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-autobahn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385437",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371802"
    ],
    "summaries": [
      "python-autobahn: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-autobahn+twisted, python3-autobahn"
    ]
  },
  "python-aws-sam-translator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353126"
    ],
    "summaries": [
      "python-aws-sam-translator fails to build with Python 3.14: 77 test failures, 4 error"
    ]
  },
  "python-colcon-meson": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368744"
    ],
    "summaries": [
      "python-colcon-meson fails to build with Meson 1.8.0: test_capital_case: TypeError: InterpreterBase.__init__() missing 2 required positional arguments: 'subproject_dir' and 'env'"
    ]
  },
  "python-daphne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385451",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371851"
    ],
    "summaries": [
      "python-daphne: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-daphne"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-datalad": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385452",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371854"
    ],
    "summaries": [
      "python-datalad: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-datalad"
    ]
  },
  "python-eventlet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385466",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371893"
    ],
    "summaries": [
      "python-eventlet: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-eventlet"
    ]
  },
  "python-ffc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385467",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371902"
    ],
    "summaries": [
      "python-ffc: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-ffc"
    ]
  },
  "python-fsleyes": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385470",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371912"
    ],
    "summaries": [
      "python-fsleyes: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-fsleyes"
    ]
  },
  "python-fsleyes-props": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385472",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371913"
    ],
    "summaries": [
      "python-fsleyes-props: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-fsleyes-props"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-jsons": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385477",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371957"
    ],
    "summaries": [
      "python-jsons: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-jsons"
    ]
  },
  "python-nipype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385502",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372004"
    ],
    "summaries": [
      "python-nipype: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-nipype+data, python3-nipype+duecredit, python3-nipype+nipy, python3-nipype+pybids, python3-nipype+ssh, python3-nipype"
    ]
  },
  "python-optking": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385505",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372017"
    ],
    "summaries": [
      "python-optking: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-optking"
    ]
  },
  "python-oslo-middleware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385506",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2347032"
    ],
    "summaries": [
      "python-oslo-middleware: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-oslo-middleware"
    ]
  },
  "python-pamela": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366474"
    ],
    "summaries": [
      "python-pamela fails to build with Python 3.14: pamela.PAMError: [PAM Error 26] Critical error - immediate abort"
    ]
  },
  "python-pingouin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385509",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372029"
    ],
    "summaries": [
      "python-pingouin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pingouin"
    ]
  },
  "python-plotnine": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385511",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372035"
    ],
    "summaries": [
      "python-plotnine: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-plotnine+extra, python3-plotnine"
    ]
  },
  "python-pocketlint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385512",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372037"
    ],
    "summaries": [
      "python-pocketlint: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pocketlint"
    ]
  },
  "python-pybids": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385515",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372050"
    ],
    "summaries": [
      "python-pybids: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pybids+plotting, python3-pybids+test, python3-pybids+tests, python3-pybids"
    ]
  },
  "python-pysaml2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385525",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372073"
    ],
    "summaries": [
      "python-pysaml2: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pysaml2"
    ]
  },
  "python-qcelemental": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385528",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372089"
    ],
    "summaries": [
      "python-qcelemental: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qcelemental"
    ]
  },
  "python-qemu-qmp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385531",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372091"
    ],
    "summaries": [
      "python-qemu-qmp: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qemu-qmp"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-sqlmodel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385537",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372150"
    ],
    "summaries": [
      "python-sqlmodel: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-sqlmodel, python3-sqlmodel-slim"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-wxnatpy": {
    "urls": [],
    "summaries": []
  },
  "python-xbout": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385555",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372202"
    ],
    "summaries": [
      "python-xbout: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-xbout"
    ]
  },
  "qtile-extras": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385564",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372210"
    ],
    "summaries": [
      "qtile-extras: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: qtile-extras"
    ]
  },
  "rpm-head-signing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366308"
    ],
    "summaries": [
      "rpm-head-signing: FTBFS in Fedora Rawhide with RPM 6"
    ]
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385672",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f43",
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "thonny": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372232"
    ],
    "summaries": [
      "F43FailsToInstall: thonny"
    ]
  },
  "zeek": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366467"
    ],
    "summaries": [
      "zeek fails to build in Fedora Rawhide: Could not find prerequisite package 'BIND'"
    ]
  }
}