{
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "buildbot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384488",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371686"
    ],
    "summaries": [
      "buildbot: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: buildbot-master, buildbot-master-container, buildbot-master-ec2, buildbot-master-libvirt, buildbot-master-openstack, buildbot-worker, buildbot-www"
    ]
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "dolfin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384554",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371707"
    ],
    "summaries": [
      "dolfin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-dolfin"
    ]
  },
  "libpeas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366247"
    ],
    "summaries": [
      "libpeas fails to build with Python 3.14: test-extension-py  TIMEOUT"
    ]
  },
  "mailman3-fedmsg-plugin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385168",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2304216"
    ],
    "summaries": [
      "mailman3-fedmsg-plugin: FTBFS in Fedora rawhide/f43",
      "F41FailsToInstall: python3-mailman3-fedmsg-plugin"
    ]
  },
  "matrix-synapse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385171",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371743"
    ],
    "summaries": [
      "matrix-synapse: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: Multiple packages built from matrix-synapse"
    ]
  },
  "mirrormanager2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385192",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2347031"
    ],
    "summaries": [
      "mirrormanager2: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: mirrormanager2"
    ]
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "paraview": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385379"
    ],
    "summaries": [
      "paraview: FTBFS in Fedora rawhide/f43"
    ]
  },
  "psi4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385428",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371776"
    ],
    "summaries": [
      "psi4: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: psi4"
    ]
  },
  "python-autobahn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385437",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371802"
    ],
    "summaries": [
      "python-autobahn: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-autobahn+twisted, python3-autobahn"
    ]
  },
  "python-colcon-meson": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368744"
    ],
    "summaries": [
      "python-colcon-meson fails to build with Meson 1.8.0: test_capital_case: TypeError: InterpreterBase.__init__() missing 2 required positional arguments: 'subproject_dir' and 'env'"
    ]
  },
  "python-daphne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385451",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371851"
    ],
    "summaries": [
      "python-daphne: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-daphne"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-eventlet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385466",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371893"
    ],
    "summaries": [
      "python-eventlet: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-eventlet"
    ]
  },
  "python-ffc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385467",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371902"
    ],
    "summaries": [
      "python-ffc: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-ffc"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-optking": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385505",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372017"
    ],
    "summaries": [
      "python-optking: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-optking"
    ]
  },
  "python-pamela": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366474"
    ],
    "summaries": [
      "python-pamela fails to build with Python 3.14: pamela.PAMError: [PAM Error 26] Critical error - immediate abort"
    ]
  },
  "python-pingouin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385509",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372029"
    ],
    "summaries": [
      "python-pingouin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pingouin"
    ]
  },
  "python-qcengine": {
    "urls": [],
    "summaries": []
  },
  "python-qemu-qmp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385531",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372091"
    ],
    "summaries": [
      "python-qemu-qmp: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qemu-qmp"
    ]
  },
  "python-sqlmodel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385537",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372150"
    ],
    "summaries": [
      "python-sqlmodel: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-sqlmodel, python3-sqlmodel-slim"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-xbout": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385555",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372202"
    ],
    "summaries": [
      "python-xbout: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-xbout"
    ]
  },
  "qtile-extras": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385564",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372210"
    ],
    "summaries": [
      "qtile-extras: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: qtile-extras"
    ]
  },
  "rpm-head-signing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366308"
    ],
    "summaries": [
      "rpm-head-signing: FTBFS in Fedora Rawhide with RPM 6"
    ]
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385672",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f43",
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "zeek": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366467"
    ],
    "summaries": [
      "zeek fails to build in Fedora Rawhide: Could not find prerequisite package 'BIND'"
    ]
  }
}